# 鉴别靶纸时用于限定轮廓面积
MINAREA = 5000
MAXAREA = 130000
# 鉴定靶纸时的高/宽
WIDTH_HEIGHT_RATION_HIGH = 1.1
WIDTH_HEIGHT_RATION_LOW = 0.5
# by AI
A4_ASPECT_RATIO = 0.7
ASPECT_RATIO_TOLERANCE = 0.2

# 多边形拟合的参数
EPSILON_RATION = 0.1
